[output_viewing]
mode = "webui"
webui_base_url = "https://ta-tools-dashboard.vercel.app"

[llm.models.general_analysis]
sdk = "openrouter"
model_name = ""
max_completion_tokens = 20000
temperature = 0.9
top_p = 1
frequency_penalty = 0
presence_penalty = 0
reasoning_effort = "high"

[llm.models.output_comparison]
sdk = "openrouter"
model_name = ""
max_completion_tokens = 20000
temperature = 0
top_p = 1
frequency_penalty = 0
presence_penalty = 0
reasoning_effort = "high"

[llm.prompt_replacement]
role = "role_placeholder"

[vendors.openrouter]
api_key = ""

[[analysis_workflows]]
slug = ""
model = "general_analysis"
runs = 1
output_filename = ""
prompt = ""

[[analysis_workflows.input_files_searches]]
file_glob = ""
search_directory = "."
excluded_files = []

[[testing_workflows]]
slug = ""
model = "general_analysis"
runs = 1
output_filename = ""
setup_commands = []
cleanup_commands = []

[[testing_workflows.test_cases]]
name = ""
work_directory = "."
single_run_command = ""
interactive_steps = []

[testing_workflows.test_cases.single_run_expected_output]
prefix_strip_string = ""
postfix_strip_string = ""
substring = ""
llm_judge_input_mode = "NONE"
llm_judge_prompt = ""
