[openrouter]
api_key = ""
model = ""

[hyperparameters]
max_completion_tokens = 20000
temperature = 0.9
top_p = 1
frequency_penalty = 0
presence_penalty = 0
reasoning_effort = "high"

[[analysis_workflows]]
slug = ""
runs = 1
output_filename = ""
prompt = ""

[[analysis_workflows.input_files_searches]]
file_glob = ""
search_directory = "."
excluded_files = []

[[testing_workflows]]
slug = ""
runs = 1
output_filename = ""
setup_commands = []
cleanup_commands = []

[[testing_workflows.test_cases]]
name = ""
single_run_command = ""
interactive_steps = []

[testing_workflows.test_cases.expected_output]
substring = ""
shell_command = ""
llm_judge_prompt = ""
